-- Script para criação das tabelas do sistema de controle de ponto
-- Schema: folhaponto_user

-- Tabela setores (já deveria existir, mas incluindo para completude)
CREATE TABLE setores (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    code VARCHAR2(20) NOT NULL UNIQUE,
    parent_id NUMBER,
    manager_id NUMBER,
    description VARCHAR2(500),
    orgao VARCHAR2(255),
    logradouro VARCHAR2(255),
    numero VARCHAR2(20),
    complemento VARCHAR2(100),
    bairro VARCHAR2(100),
    cidade VARCHAR2(100),
    estado VARCHAR2(2),
    cep VARCHAR2(9),
    telefone VARCHAR2(20),
    email VARCHAR2(255),
    latitude NUMBER(10,8),
    longitude NUMBER(11,8),
    active NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_setores_parent FOREIGN KEY (parent_id) REFERENCES setores(id),
    CONSTRAINT fk_setores_manager FOREIGN KEY (manager_id) REFERENCES usuarios(id)
);

-- Tabela dados_pessoais
CREATE TABLE dados_pessoais (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL UNIQUE,
    pis_pasep VARCHAR2(15),
    sexo CHAR(1) CHECK (sexo IN ('M', 'F')),
    estado_civil VARCHAR2(20),
    data_nascimento DATE,
    pai VARCHAR2(255),
    mae VARCHAR2(255),
    rg VARCHAR2(20),
    tipo_rg VARCHAR2(50),
    orgao_expeditor VARCHAR2(10),
    uf_rg CHAR(2),
    expedicao_rg DATE,
    cidade_nascimento VARCHAR2(100),
    uf_nascimento CHAR(2),
    tipo_sanguineo VARCHAR2(5),
    raca_cor VARCHAR2(20),
    pne NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dados_pessoais_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Tabela dados_profissionais
CREATE TABLE dados_profissionais (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL UNIQUE,
    num_func VARCHAR2(20),
    num_vinc VARCHAR2(20),
    tipo_vinculo VARCHAR2(50),
    categoria VARCHAR2(50),
    regime_jur VARCHAR2(50),
    regime_prev VARCHAR2(50),
    tipo_evento VARCHAR2(50),
    forma_prov VARCHAR2(50),
    codigo_cargo VARCHAR2(20),
    cargo VARCHAR2(100),
    escolaridade_cargo VARCHAR2(50),
    escolaridade_servidor VARCHAR2(50),
    formacao_profissional_1 VARCHAR2(255),
    formacao_profissional_2 VARCHAR2(255),
    jornada VARCHAR2(20),
    nivel_ref VARCHAR2(50),
    comissao_funcao VARCHAR2(100),
    dt_ini_comissao DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_dados_profissionais_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Tabela enderecos
CREATE TABLE enderecos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL UNIQUE,
    logradouro VARCHAR2(255),
    numero VARCHAR2(20),
    complemento VARCHAR2(100),
    bairro VARCHAR2(100),
    cidade VARCHAR2(100),
    estado CHAR(2),
    cep VARCHAR2(9),
    sem_numero NUMBER(1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_enderecos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Tabela lotacao
CREATE TABLE lotacao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL UNIQUE,
    setor_id NUMBER,
    orgao VARCHAR2(255),
    setor VARCHAR2(100),
    lotacao VARCHAR2(100),
    municipio_lotacao VARCHAR2(100),
    situacao VARCHAR2(20) DEFAULT 'ATIVO',
    hierarquia_setor VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_lotacao_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
    CONSTRAINT fk_lotacao_setor FOREIGN KEY (setor_id) REFERENCES setores(id)
);

-- Tabela registros_ponto
CREATE TABLE registros_ponto (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    data DATE NOT NULL,
    entrada TIMESTAMP,
    saida_almoco TIMESTAMP,
    retorno_almoco TIMESTAMP,
    saida TIMESTAMP,
    horas_trabalhadas INTERVAL DAY TO SECOND,
    justificativa VARCHAR2(500),
    status VARCHAR2(20) DEFAULT 'PENDENTE',
    aprovado_por NUMBER,
    data_aprovacao TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_registros_ponto_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_registros_ponto_aprovador FOREIGN KEY (aprovado_por) REFERENCES usuarios(id)
);

-- Tabela escalas
CREATE TABLE escalas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),
    setor_id NUMBER,
    tipo VARCHAR2(20) DEFAULT 'PADRAO', -- PADRAO, FLEXIVEL, PLANTAO
    jornada_padrao VARCHAR2(20) DEFAULT '8h',
    dias_trabalho VARCHAR2(50) DEFAULT '2-6', -- Ex: 2-6 (segunda a sexta)
    horario_entrada VARCHAR2(5) DEFAULT '08:00',
    horario_saida VARCHAR2(5) DEFAULT '17:00',
    horario_almoco_inicio VARCHAR2(5) DEFAULT '12:00',
    horario_almoco_fim VARCHAR2(5) DEFAULT '13:00',
    ativo NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_escalas_setor FOREIGN KEY (setor_id) REFERENCES setores(id)
);

-- Tabela feriados
CREATE TABLE feriados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    data DATE NOT NULL,
    tipo VARCHAR2(20) DEFAULT 'NACIONAL', -- NACIONAL, ESTADUAL, MUNICIPAL
    uf CHAR(2),
    municipio VARCHAR2(100),
    setor_id NUMBER,
    ativo NUMBER(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_feriados_setor FOREIGN KEY (setor_id) REFERENCES setores(id)
);

-- Tabela ocorrencias
CREATE TABLE ocorrencias (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE,
    descricao VARCHAR2(500),
    anexo VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'PENDENTE',
    aprovado_por NUMBER,
    data_aprovacao TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ocorrencias_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_ocorrencias_aprovador FOREIGN KEY (aprovado_por) REFERENCES usuarios(id)
);

-- Tabela atestados
CREATE TABLE atestados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    data_emissao DATE NOT NULL,
    data_inicio DATE NOT NULL,
    data_fim DATE NOT NULL,
    cid VARCHAR2(10),
    medico VARCHAR2(255),
    crm VARCHAR2(20),
    anexo VARCHAR2(255),
    status VARCHAR2(20) DEFAULT 'PENDENTE',
    aprovado_por NUMBER,
    data_aprovacao TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_atestados_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_atestados_aprovador FOREIGN KEY (aprovado_por) REFERENCES usuarios(id)
);

-- Tabela banco_horas
CREATE TABLE banco_horas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    data DATE NOT NULL,
    tipo VARCHAR2(20) NOT NULL, -- CREDITO, DEBITO
    horas INTERVAL DAY TO SECOND NOT NULL,
    justificativa VARCHAR2(255),
    saldo_anterior INTERVAL DAY TO SECOND,
    saldo_atual INTERVAL DAY TO SECOND,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_banco_horas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Tabela templates_formularios
CREATE TABLE templates_formularios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    descricao VARCHAR2(255),
    categoria VARCHAR2(50),
    estrutura CLOB, -- JSON com estrutura do formulário
    campos_obrigatorios VARCHAR2(1000), -- Lista de campos obrigatórios
    ativo NUMBER(1) DEFAULT 1,
    created_by NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_templates_created_by FOREIGN KEY (created_by) REFERENCES usuarios(id)
);

-- Tabela formularios
CREATE TABLE formularios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id NUMBER NOT NULL,
    usuario_id NUMBER NOT NULL,
    dados CLOB, -- JSON com dados preenchidos
    status VARCHAR2(20) DEFAULT 'RASCUNHO',
    enviado_em TIMESTAMP,
    aprovado_em TIMESTAMP,
    aprovado_por NUMBER,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_formularios_template FOREIGN KEY (template_id) REFERENCES templates_formularios(id),
    CONSTRAINT fk_formularios_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id),
    CONSTRAINT fk_formularios_aprovador FOREIGN KEY (aprovado_por) REFERENCES usuarios(id)
);

-- Tabela relatorios
CREATE TABLE relatorios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL,
    tipo VARCHAR2(50) NOT NULL,
    parametros CLOB, -- JSON com parâmetros do relatório
    resultado CLOB, -- JSON ou dados do relatório
    formato VARCHAR2(10) DEFAULT 'PDF',
    gerado_por NUMBER NOT NULL,
    gerado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    arquivo VARCHAR2(255),
    CONSTRAINT fk_relatorios_gerado_por FOREIGN KEY (gerado_por) REFERENCES usuarios(id)
);

-- Tabela setores_hierarquia
CREATE TABLE setores_hierarquia (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setor_pai_id NUMBER NOT NULL,
    setor_filho_id NUMBER NOT NULL,
    nivel NUMBER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hierarquia_pai FOREIGN KEY (setor_pai_id) REFERENCES setores(id),
    CONSTRAINT fk_hierarquia_filho FOREIGN KEY (setor_filho_id) REFERENCES setores(id),
    CONSTRAINT uk_hierarquia UNIQUE (setor_pai_id, setor_filho_id)
);

-- Tabela configuracoes_sistema
CREATE TABLE configuracoes_sistema (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chave VARCHAR2(100) NOT NULL UNIQUE,
    valor VARCHAR2(1000),
    tipo VARCHAR2(20) DEFAULT 'STRING',
    descricao VARCHAR2(255),
    modificado_por NUMBER,
    modificado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_config_modificado_por FOREIGN KEY (modificado_por) REFERENCES usuarios(id)
);

-- Tabela logs_auditoria
CREATE TABLE logs_auditoria (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabela VARCHAR2(50) NOT NULL,
    registro_id NUMBER,
    operacao VARCHAR2(10) NOT NULL, -- INSERT, UPDATE, DELETE
    usuario_id NUMBER,
    dados_anteriores CLOB,
    dados_novos CLOB,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_logs_auditoria_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);

-- Índices para performance
CREATE INDEX idx_dados_pessoais_usuario ON dados_pessoais(usuario_id);
CREATE INDEX idx_dados_profissionais_usuario ON dados_profissionais(usuario_id);
CREATE INDEX idx_enderecos_usuario ON enderecos(usuario_id);
CREATE INDEX idx_lotacao_usuario ON lotacao(usuario_id);
CREATE INDEX idx_lotacao_setor ON lotacao(setor_id);
CREATE INDEX idx_registros_ponto_usuario ON registros_ponto(usuario_id);
CREATE INDEX idx_registros_ponto_data ON registros_ponto(data);
CREATE INDEX idx_registros_ponto_status ON registros_ponto(status);
CREATE INDEX idx_escalas_setor ON escalas(setor_id);
CREATE INDEX idx_feriados_data ON feriados(data);
CREATE INDEX idx_ocorrencias_usuario ON ocorrencias(usuario_id);
CREATE INDEX idx_ocorrencias_status ON ocorrencias(status);
CREATE INDEX idx_atestados_usuario ON atestados(usuario_id);
CREATE INDEX idx_atestados_status ON atestados(status);
CREATE INDEX idx_banco_horas_usuario ON banco_horas(usuario_id);
CREATE INDEX idx_formularios_template ON formularios(template_id);
CREATE INDEX idx_formularios_usuario ON formularios(usuario_id);
CREATE INDEX idx_formularios_status ON formularios(status);
CREATE INDEX idx_relatorios_gerado_por ON relatorios(gerado_por);
CREATE INDEX idx_setores_hierarquia_pai ON setores_hierarquia(setor_pai_id);
CREATE INDEX idx_setores_hierarquia_filho ON setores_hierarquia(setor_filho_id);
CREATE INDEX idx_logs_auditoria_tabela ON logs_auditoria(tabela);
CREATE INDEX idx_logs_auditoria_usuario ON logs_auditoria(usuario_id);
CREATE INDEX idx_logs_auditoria_created ON logs_auditoria(created_at);

COMMIT;

-- Mensagem de confirmação
SELECT 'Tabelas criadas com sucesso no schema folhaponto_user' as status FROM dual;