-- Schema para Sistema de Controle de Ponto - SEFAZ-TO
-- Criação das tabelas principais para autenticação e controle de acesso

-- Tabela de Usuários
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(255) NOT NULL UNIQUE,
    senha_hash VARCHAR2(255) NOT NULL,
    nome VARCHAR2(255) NOT NULL,
    cpf VARCHAR2(14) UNIQUE,
    matricula VARCHAR2(20) UNIQUE,
    perfil VARCHAR2(50) NOT NULL CHECK (perfil IN ('SERVIDOR', 'CHEFIA', 'RH', 'ADMIN')),
    departamento VARCHAR2(100),
    cargo VARCHAR2(100),
    ativo NUMBER(1) DEFAULT 1 CHECK (ativo IN (0, 1)),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ultimo_login TIMESTAMP,
    tentativas_login NUMBER DEFAULT 0,
    bloqueado_ate TIMESTAMP
);

-- Tabela de Sessões
CREATE TABLE sessoes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER NOT NULL,
    token_hash VARCHAR2(255) NOT NULL,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    data_expiracao TIMESTAMP NOT NULL,
    ativo NUMBER(1) DEFAULT 1 CHECK (ativo IN (0, 1)),
    CONSTRAINT fk_sessoes_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);

-- Tabela de Permissões
CREATE TABLE permissoes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR2(100) NOT NULL UNIQUE,
    descricao VARCHAR2(255),
    modulo VARCHAR2(50) NOT NULL,
    acao VARCHAR2(50) NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Perfis e Permissões (Many-to-Many)
CREATE TABLE perfil_permissoes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil VARCHAR2(50) NOT NULL,
    permissao_id NUMBER NOT NULL,
    data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_perfil_permissao FOREIGN KEY (permissao_id) REFERENCES permissoes(id) ON DELETE CASCADE
);

-- Tabela de Auditoria de Login
CREATE TABLE auditoria_login (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id NUMBER,
    email VARCHAR2(255) NOT NULL,
    ip_address VARCHAR2(45),
    user_agent VARCHAR2(500),
    sucesso NUMBER(1) NOT NULL CHECK (sucesso IN (0, 1)),
    motivo_falha VARCHAR2(255),
    data_tentativa TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Índices para performance
CREATE INDEX idx_usuarios_email ON usuarios(email);
CREATE INDEX idx_usuarios_perfil ON usuarios(perfil);
CREATE INDEX idx_sessoes_token ON sessoes(token_hash);
CREATE INDEX idx_sessoes_usuario ON sessoes(usuario_id);
CREATE INDEX idx_auditoria_usuario ON auditoria_login(usuario_id);
CREATE INDEX idx_auditoria_data ON auditoria_login(data_tentativa);

-- Trigger para atualizar data_atualizacao
CREATE OR REPLACE TRIGGER trg_usuarios_updated
    BEFORE UPDATE ON usuarios
    FOR EACH ROW
BEGIN
    :NEW.data_atualizacao := CURRENT_TIMESTAMP;
END;

-- Inserir permissões básicas
INSERT INTO permissoes (nome, descricao, modulo, acao) VALUES 
('DASHBOARD_VIEW', 'Visualizar dashboard', 'DASHBOARD', 'VIEW'),
('PONTO_REGISTRAR', 'Registrar ponto', 'PONTO', 'CREATE'),
('PONTO_VIEW', 'Visualizar registros de ponto', 'PONTO', 'VIEW'),
('OCORRENCIAS_CREATE', 'Criar ocorrências', 'OCORRENCIAS', 'CREATE'),
('OCORRENCIAS_VIEW', 'Visualizar ocorrências', 'OCORRENCIAS', 'VIEW'),
('OCORRENCIAS_APPROVE', 'Aprovar ocorrências', 'OCORRENCIAS', 'APPROVE'),
('RELATORIOS_VIEW', 'Visualizar relatórios', 'RELATORIOS', 'VIEW'),
('RELATORIOS_EXPORT', 'Exportar relatórios', 'RELATORIOS', 'EXPORT'),
('USUARIOS_MANAGE', 'Gerenciar usuários', 'USUARIOS', 'MANAGE'),
('SISTEMA_CONFIG', 'Configurar sistema', 'SISTEMA', 'CONFIG'),
('AUDITORIA_VIEW', 'Visualizar auditoria', 'AUDITORIA', 'VIEW');

-- Associar permissões aos perfis
-- SERVIDOR
INSERT INTO perfil_permissoes (perfil, permissao_id) 
SELECT 'SERVIDOR', id FROM permissoes WHERE nome IN (
    'DASHBOARD_VIEW', 'PONTO_REGISTRAR', 'PONTO_VIEW', 
    'OCORRENCIAS_CREATE', 'OCORRENCIAS_VIEW', 'RELATORIOS_VIEW'
);

-- CHEFIA
INSERT INTO perfil_permissoes (perfil, permissao_id) 
SELECT 'CHEFIA', id FROM permissoes WHERE nome IN (
    'DASHBOARD_VIEW', 'PONTO_VIEW', 'OCORRENCIAS_VIEW', 
    'OCORRENCIAS_APPROVE', 'RELATORIOS_VIEW', 'RELATORIOS_EXPORT'
);

-- RH
INSERT INTO perfil_permissoes (perfil, permissao_id) 
SELECT 'RH', id FROM permissoes WHERE nome IN (
    'DASHBOARD_VIEW', 'PONTO_VIEW', 'OCORRENCIAS_VIEW', 
    'OCORRENCIAS_APPROVE', 'RELATORIOS_VIEW', 'RELATORIOS_EXPORT',
    'USUARIOS_MANAGE', 'AUDITORIA_VIEW'
);

-- ADMIN
INSERT INTO perfil_permissoes (perfil, permissao_id) 
SELECT 'ADMIN', id FROM permissoes;

COMMIT;