-- Dados iniciais para testes - Sistema de Controle de Ponto SEFAZ-TO
-- Inserção dos usuários de teste com as credenciais especificadas

-- Limpar dados existentes (se houver)
DELETE FROM perfil_permissoes;
DELETE FROM auditoria_login;
DELETE FROM sessoes;
DELETE FROM usuarios;

-- Resetar sequences (Oracle)
ALTER TABLE usuarios MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE sessoes MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);
ALTER TABLE auditoria_login MODIFY id GENERATED BY DEFAULT AS IDENTITY (START WITH 1);

-- Inserir usuários de teste
-- Senha: 123456 (hash bcrypt com salt 10: $2b$10$rOzJqQjQjQjQjQjQjQjQjOeKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK)
-- Hash real será gerado pelo backend

INSERT INTO usuarios (
    email, 
    senha_hash, 
    nome, 
    cpf, 
    matricula, 
    perfil, 
    departamento, 
    cargo, 
    ativo
) VALUES 
(
    'joao.silva@sefaz.to.gov.br',
    '$2b$10$rOzJqQjQjQjQjQjQjQjQjOeKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK', -- Será atualizado pelo backend
    'João Silva',
    '123.456.789-01',
    'SRV001',
    'SERVIDOR',
    'Fiscalização',
    'Auditor Fiscal',
    1
),
(
    'maria.santos@sefaz.to.gov.br',
    '$2b$10$rOzJqQjQjQjQjQjQjQjQjOeKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK', -- Será atualizado pelo backend
    'Maria Santos',
    '234.567.890-12',
    'CHF001',
    'CHEFIA',
    'Fiscalização',
    'Chefe de Seção',
    1
),
(
    'carlos.oliveira@sefaz.to.gov.br',
    '$2b$10$rOzJqQjQjQjQjQjQjQjQjOeKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK', -- Será atualizado pelo backend
    'Carlos Oliveira',
    '345.678.901-23',
    'RH001',
    'RH',
    'Recursos Humanos',
    'Analista de RH',
    1
),
(
    'ana.paula@sefaz.to.gov.br',
    '$2b$10$rOzJqQjQjQjQjQjQjQjQjOeKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK', -- Será atualizado pelo backend
    'Ana Paula',
    '456.789.012-34',
    'ADM001',
    'ADMIN',
    'TI',
    'Administrador de Sistema',
    1
);

-- Inserir alguns dados de exemplo para auditoria (opcional)
INSERT INTO auditoria_login (
    usuario_id,
    email,
    ip_address,
    user_agent,
    sucesso,
    motivo_falha,
    data_tentativa
) VALUES 
(1, 'joao.silva@sefaz.to.gov.br', '192.168.1.100', 'Mozilla/5.0', 1, NULL, CURRENT_TIMESTAMP - INTERVAL '1' DAY),
(2, 'maria.santos@sefaz.to.gov.br', '192.168.1.101', 'Mozilla/5.0', 1, NULL, CURRENT_TIMESTAMP - INTERVAL '2' HOUR),
(3, 'carlos.oliveira@sefaz.to.gov.br', '192.168.1.102', 'Mozilla/5.0', 1, NULL, CURRENT_TIMESTAMP - INTERVAL '30' MINUTE),
(4, 'ana.paula@sefaz.to.gov.br', '192.168.1.103', 'Mozilla/5.0', 1, NULL, CURRENT_TIMESTAMP - INTERVAL '10' MINUTE);

COMMIT;

-- Verificar dados inseridos
SELECT 
    id,
    email,
    nome,
    perfil,
    departamento,
    cargo,
    ativo,
    data_criacao
FROM usuarios
ORDER BY id;